### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by aamishi** [davidpxrk/cost-of-living-toronto#1]
Hey! I think that you have a very well put together paper, good job! I went through your paper against the rubric, and I think you have most of the checks completed. However, you still have to change the name of the .proj file to something more relevant to your paper. Update all if your scripts to remove all # [...UPDATE THIS...] comments from the starer code. Also, this paper does not require a model, so you should remove it from your scripts. You also need to add some simulations. Include the other folders from the Rohan's starter_folder to include your sketches and LLM statements. Based on the progress of your paper, I think that you maybe aware of these points, so well done!

Overall I think that you are on the right path with your paper, the abstract and introduction introduce the main idea well and the data and results section is also well connected and coherent. You only have minor changes left to go. All the best!

Estimated mark: 88/100

**Comment by davidpxrk** [comment]
I have removed all the unnecessary code and updated the .proj file, sketches and the simulation. Thanks for your feedback!
