### ISSUE TITLE
Rob's Peer Review

### ISSUE THREAD

**Issue by Ford-Robert** [davidpxrk/cost-of-living-toronto#3]
Opening statement summary:
Reviewing the github files for this paper. Looks like some sections are incomplete, however on the whole it looks like you have made significant progress.

Strong positive points:

Very strong abstract and introduction. The data cleaning is comprehensive.

Critical improvements needed:

  -Add a simulation data set, and you need to test the quality of your data to ensure it does not contain unexpected values!
  
  -Need to add a folder that contains the sketches of your graphs and tables
  
  -Need to fix the captions of the graphs. The caption of the bar chart is "Figure 1: Figure 5: ..."
  
  -Need to fix pie chart

Suggestions for improvement:

  -For the first bar chart (Figure 1: Figure 5:), consider changing the x-axis so that is follows some pattern. Maybe you order them by highest income, or by household number, or highest expense (my preferred). I think this would make the graph look nicer.
  
 -Looking at the cleaned data (in particular the Percentage of income required for rent row), I think a really cool chart would be, maybe its a bad chart but worth trying. Make a bar graph where the y-axis is the percentage of income, and each bar is a different house_hold. Then draw a horizontal red line at the 30% line (commonly recommended as the most you should spend on housing). This chart really show how bad things are for these households. You could do the same for the next row (Percentage of income required to purchase healthy food), and draw the red line where the canadian gov recommends how much should be spent on food.

Please consider adding/changing/removing:
Add those two graphs! ;)

Evaluation:
All and all a very good paper that has a ton of valuable insights and data!

Estimated mark:

Grade Estimation (Breakdown by Rubric)

R is cited (1/1)
LLM usage is documented (1/1)
Title (2/2)
Author, date, and repo (2/2)
Abstract (4/4)
Introduction (4/4)
Data (10/10)
Measurement (4/4)
Cross-references (0/2): Fig's need fixing!
Prose (6/6)
Graphs/tables/etc (3/4)
Referencing (4/4)
Commits (2/2)
Sketches (0/2)
Simulation (0/4)
Tests (0/4)
Reproducibility (4/4)
Code style (1/1)
General excellence (2/3): Could be excellent!

Overall 50/64

Reason: Overall a very good paper. Mostly just missing a few critical sections, otherwise looking very good to go!

**Comment by davidpxrk** [comment]
Changed the graphs as pointed out, thanks for your feedback :)
